import sys
import os
import shutil


PSEUDO_HOME = os.path.join(os.path.expanduser('~'), '.pseudo')

def setup_home():
    """Create ~/.pseudo/ structure and install core .pmap files."""
    dirs = [
        os.path.join(PSEUDO_HOME, 'core'),
        os.path.join(PSEUDO_HOME, 'custom'),
        os.path.join(PSEUDO_HOME, 'cache'),
        os.path.join(PSEUDO_HOME, 'packages'),
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)

    # Always copy bundled default.pmap to ~/.pseudo/core/ (keep up to date)
    if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
        bundled = os.path.join(sys._MEIPASS, 'pseudo', 'data', 'default.pmap')
    else:
        here = os.path.dirname(os.path.abspath(__file__))
        bundled = os.path.join(here, 'data', 'default.pmap')
    dest_core = os.path.join(PSEUDO_HOME, 'core', 'default.pmap')

    if os.path.exists(bundled):
        shutil.copy2(bundled, dest_core)
        # Invalidate cache when pmap is updated
        cache_file = os.path.join(PSEUDO_HOME, 'cache', 'default.pmap.cache')
        if os.path.exists(cache_file):
            os.remove(cache_file)

    # Create custom.pmap if missing - with @inherit so default patterns load
    custom_pmap = os.path.join(PSEUDO_HOME, 'custom', 'custom.pmap')
    if not os.path.exists(custom_pmap):
        _write_custom_template(custom_pmap)
    else:
        # Repair existing custom.pmap if it's missing @inherit
        _ensure_inherit(custom_pmap)

    # Write config.json if missing
    config_path = os.path.join(PSEUDO_HOME, 'config.json')
    if not os.path.exists(config_path):
        import json
        with open(config_path, 'w') as f:
            json.dump({
                'version': '1.0',
                'default_timeout': 5,
                'default_max_iter': 10000000,
            }, f, indent=2)


def _write_custom_template(path: str):
    template = """\
@pmap-version 1.0
@pseudo-version >=1.0 <2.0
@language "Custom"
@author ""
@inherit default.pmap

# ─────────────────────────────────────────────────────────────
# Custom mapping file - generated by: pseudo init
#
# This file APPENDS to default.pmap (your patterns tried FIRST).
# Remove or change @inherit to fully replace the default.
# ─────────────────────────────────────────────────────────────

"""
    with open(path, 'w', encoding='utf-8') as f:
        f.write(template)


def _ensure_inherit(path: str):
    """Add @inherit default.pmap to an existing custom.pmap if missing."""
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    if '@inherit' not in content:
        # Insert after the @author line or after header block
        lines = content.splitlines(keepends=True)
        insert_at = 0
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith('@') and not stripped.startswith('@inherit'):
                insert_at = i + 1
        lines.insert(insert_at, '@inherit default.pmap\n')
        with open(path, 'w', encoding='utf-8') as f:
            f.writelines(lines)
