import type { Metadata } from "next";
import CodeBlock from "../components/CodeBlock";

export const metadata: Metadata = { title: "Custom PMAP" };

const TEMPLATE = `@pmap-version 1.0
@pseudo-version >=1.0 <2.0
@language "Custom"
@author ""
@inherit default.pmap

# ─────────────────────────────────────────────────────────────
# Custom mapping file — generated by: pseudo init
#
# This file APPENDS to default.pmap (patterns tried FIRST).
# Remove or change @inherit to fully replace the default.
#
# PLACEHOLDER TYPES:
#   {name:name}        single identifier word
#   {value:expr}       full expression
#   {n:number}         numeric literal only
#   {condition:expr}   boolean expression
#   {type:word}        single type keyword
#   {collection:expr}  iterable expression
#   {text:any}         everything to end of line
# ─────────────────────────────────────────────────────────────

# Example: add new ways to write a for loop
# [FOR_LOOP]
# go through {var:name} from {start:expr} to {end:expr}
# count {var:name} from {start:expr} until {end:expr}

# Example: completely replace how PRINT works
# [PRINT] @replace
# yell {value:expr}
# scream {value:expr}`;

const CUSTOM_PMAP = `@pmap-version 1.0
@pseudo-version >=1.0 <2.0
@language "Tamil"
@author "example"
@inherit default.pmap

[PRINT]
sollu {value:expr}
kaatu {value:expr}

[FOR_LOOP]
for {var:name} irundu {start:expr} varai {end:expr}

[IF]
@context TOP_LEVEL FUNCTION_BODY LOOP_BODY IF_BODY
endral {condition:expr}`;

const REPLACE_EXAMPLE = `@pmap-version 1.0
@language "Kids"
@inherit default.pmap

# Completely replace PRINT with kid-friendly words
[PRINT] @replace
say {value:expr}
yell {value:expr}
whisper {value:expr}

# Add to existing FOR_EACH (doesn't replace)
[FOR_EACH]
go through each {item:name} in {collection:expr}`;

export default function CustomPmapPage() {
  return (
    <>
      <div className="topbar">
        <span className="topbar-title">
          PMAP System › <span>Custom PMAP</span>
        </span>
        <span className="topbar-badge">v0.1</span>
      </div>
      <div className="page">
        <div className="page-hero">
          <span className="page-label">The PMAP System</span>
          <h1 className="page-title">Creating a Custom PMAP</h1>
          <p className="page-desc">
            Write pseudo in any style or language by defining your own{" "}
            <code>.pmap</code> mapping file.
          </p>
        </div>

        <h2>1. Initialize</h2>
        <p>
          The easiest way to start is via <code>pseudo init</code>:
        </p>
        <CodeBlock lang="bash" code="pseudo init" />
        <p>
          This creates a <code>custom.pmap</code> template at the path you
          specify and a <code>pseudo.config</code> linking to it.
        </p>

        <h2>2. The Template File</h2>
        <CodeBlock code={TEMPLATE} lang="text" title="custom.pmap" />

        <h2>3. PMAP File Structure</h2>
        <p>
          Every <code>.pmap</code> file must contain:
        </p>
        <ol style={{ color: "var(--fg-muted)" }}>
          <li>
            <strong style={{ color: "var(--fg-light)" }}>
              Metadata headers
            </strong>{" "}
            — at the top
          </li>
          <li>
            <strong style={{ color: "var(--fg-light)" }}>
              Section headers
            </strong>{" "}
            — <code>[CANONICAL_NAME]</code>
          </li>
          <li>
            <strong style={{ color: "var(--fg-light)" }}>Pattern lines</strong>{" "}
            — one per line, below the section header
          </li>
        </ol>

        <h2>4. Adding New Mappings</h2>
        <p>
          To add a new way to write a <code>FOR_LOOP</code>:
        </p>
        <CodeBlock
          lang="text"
          code={`[FOR_LOOP]
go through {var:name} from {start:expr} to {end:expr}
count {var:name} from {start:expr} until {end:expr}`}
        />
        <p>
          Your patterns are tried <strong>before</strong> the default patterns
          (higher priority).
        </p>

        <h2>5. Inherit Modes</h2>
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Directive</th>
                <th>Behavior</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <code>@inherit default.pmap</code>
                </td>
                <td>
                  <strong>APPEND</strong> (default): your patterns tried first,
                  then default patterns
                </td>
              </tr>
              <tr>
                <td>
                  <code>@inherit default.pmap REPLACE</code>
                </td>
                <td>Your section completely replaces the parent section</td>
              </tr>
              <tr>
                <td>
                  <code>@inherit default.pmap PREPEND</code>
                </td>
                <td>Default patterns tried first, yours second</td>
              </tr>
              <tr>
                <td>
                  <code>@ignore-default</code>
                </td>
                <td>Ignore ALL default patterns — only your patterns used</td>
              </tr>
            </tbody>
          </table>
        </div>

        <h2>6. Section-level Replace</h2>
        <p>
          Use <code>@replace</code> on a single section header to only replace
          that canonical:
        </p>
        <CodeBlock lang="text" code={REPLACE_EXAMPLE} />

        <h2>7. Full Example — Tamil Language</h2>
        <CodeBlock code={CUSTOM_PMAP} lang="text" title="tamil.pmap" />
        <p>Use it by running:</p>
        <CodeBlock
          lang="bash"
          code="pseudo run program.pseudo --lang tamil.pmap"
        />
        <p>
          Or name your file <code>algo.tamil.pseudo</code> to auto-load it.
        </p>

        <h2>8. Validate Your PMAP</h2>
        <CodeBlock
          lang="bash"
          code="pseudo validate custom.pmap"
          showOutput={`Validating custom.pmap...
  ✓ 8 patterns loaded.
  No errors found.`}
        />

        <h2>PMAP Security Rules</h2>
        <div className="callout warn">
          <span className="callout-icon">⚠</span>
          <div className="callout-body">
            <strong>.pmap files are data only</strong>
            They cannot execute code, access the filesystem, make network calls,
            or add new canonical structures. Anything outside the whitelist
            causes the file to be rejected entirely.
          </div>
        </div>

        <h2>Conflict Detection</h2>
        <p>
          At load time, if two patterns in the same canonical section can match
          the same input, Pseudo warns about unreachable patterns:
        </p>
        <CodeBlock
          lang="text"
          code={`⚠ Conflict in [FOR_LOOP]: pattern "loop {var:name} from {start:expr} to {end:expr}"
  is unreachable — "for {var:name} from {start:expr} to {end:expr}" already matches.
  The first pattern always wins.`}
        />
      </div>
    </>
  );
}
